import { z } from 'zod';
import {
  AbilityEffectSchema,
  AttackRollSchema,
  AuraDefinitionSchema,
  CooldownSchema,
  RangeSchema,
  ResourceCostSchema,
  rarity,
  SavingThrowSchema,
  StatModifierBlockSchema,
  TargetingSchema,
  TriggerDefinitionSchema,
} from './common';

export const ActiveAbilitySystemSchema = z.object({
  category: z.literal('active'),
  kind: z.literal('ability').default('ability'),
  name: z.string().default(''),
  description: z.string().default(''),
  weight: z.number().default(0),
  rarity,
  activeKind: z.enum([
    'attack',
    'heal',
    'support',
    'debuff',
    'control',
    'movement',
    'summon',
    'utility',
  ]),
  actionType: z.enum(['action', 'bonus', 'reaction', 'free']).default('action'),
  castTime: z.number().optional(),
  range: RangeSchema,
  targeting: TargetingSchema,
  cooldown: CooldownSchema.nullable().default(null),
  resourceCosts: z.array(ResourceCostSchema).default([]),
  maxRank: z.number().default(1),
  currentRank: z.number().default(1),
  attackRoll: AttackRollSchema.nullable().optional(),
  savingThrow: SavingThrowSchema.nullable().optional(),
  effects: z.array(AbilityEffectSchema).default([]),
  channeled: z.boolean().optional(),
  togglable: z.boolean().optional(),
  usesPerRest: z.number().nullable().optional(),
  usesPerEncounter: z.number().nullable().optional(),
});

export const PassiveAbilitySystemSchema = z.object({
  category: z.literal('passive'),
  kind: z.literal('ability').default('ability'),
  name: z.string().default(''),
  description: z.string().default(''),
  weight: z.number().default(0),
  rarity,
  passiveKind: z.enum(['stat-bonus', 'aura', 'triggered', 'mechanic']),
  mode: z.enum(['always-on', 'toggle', 'triggered']).default('always-on'),
  cooldown: CooldownSchema.nullable().default(null),
  resourceCosts: z.array(ResourceCostSchema).default([]),
  maxRank: z.number().default(1),
  currentRank: z.number().default(1),
  statBonuses: StatModifierBlockSchema.nullable().optional(),
  aura: AuraDefinitionSchema.nullable().optional(),
  triggers: z.array(TriggerDefinitionSchema).nullable().optional(),
});

export const AbilitySystemSchema = z.discriminatedUnion('category', [
  ActiveAbilitySystemSchema,
  PassiveAbilitySystemSchema,
]);
