import { z } from 'zod';
import {
  AbilityEffectSchema,
  AttackRollSchema,
  CooldownSchema,
  RangeSchema,
  ResourceCostSchema,
  rarity,
  SavingThrowSchema,
  TargetingSchema,
} from './common';

export const SpellSystemSchema = z.object({
  category: z.enum(['code', 'elemental', 'dark', 'holy', 'arcane']),
  spellKind: z.enum([
    'attack',
    'heal',
    'support',
    'debuff',
    'control',
    'movement',
    'summon',
    'utility',
  ]),
  kind: z.literal('spell').default('spell'),
  name: z.string().default(''),
  description: z.string().default(''),
  weight: z.number().default(0),
  rarity,
  actionType: z.enum(['action', 'bonus', 'reaction', 'free']).default('action'),
  resourceCosts: z.array(ResourceCostSchema).default([]),
  castTime: z.number().default(0),
  range: RangeSchema,
  targeting: TargetingSchema,
  attackRoll: AttackRollSchema.nullable().optional(),
  savingThrow: SavingThrowSchema.nullable().optional(),
  effects: z.array(AbilityEffectSchema).default([]),
  channeled: z.boolean().optional(),
  togglable: z.boolean().optional(),
  usesPerRest: z.number().nullable().optional(),
  usesPerEncounter: z.number().nullable().optional(),
  cooldown: CooldownSchema.nullable().default(null),
  maxRank: z.number().default(1),
  currentRank: z.number().default(1),
});
